"""Orchestrates one generation pass: world → data/<world>/ (+ storyline variants) → manifest → validator."""
from __future__ import annotations

import copy
import random
import shutil
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

import yaml

from .manifest import build_manifest
from .render_eml import RenderedMessage, render_bulk_item, render_thread, write_eml
from .render_ics import write_calendars
from .render_notes import write_notes, write_tasks
from .timeline import TZ, Timeline
from .validate import (
    Report,
    check_counts,
    check_inbox,
    check_manifest_refs,
    check_must_include,
    check_prose_words,
    check_reviewed,
    check_storyline_coverage,
)
from .world import World, load_world

REPO = Path(__file__).resolve().parents[1]


@dataclass
class BuildResult:
    data_dir: Path
    manifest_path: Path | None
    report: Report
    emails: int
    variants: list[Path]


def _apply_variant(w: World, variant_id: str) -> World:
    """Return a copy of the world with the storyline variant's extra prose messages appended to their threads."""
    w2 = copy.copy(w)
    w2.threads = copy.deepcopy(w.threads)
    vdir = w.path / "prose" / "variants" / variant_id
    for f in sorted(vdir.glob("*.yaml")):
        with open(f, encoding="utf-8") as fh:
            extra = yaml.safe_load(fh)
        t = next(x for x in w2.threads if x["thread_id"] == extra["thread_id"])
        t["messages"] = t["messages"] + extra["messages"]
    return w2


def render_world(w: World, tl: Timeline, out: Path, seed: int, corrupt_ics: bool = False):
    if out.exists():
        shutil.rmtree(out)
    inbox = out / "inbox"
    inbox.mkdir(parents=True)
    rng = random.Random(seed)
    seen: set[str] = set()
    rendered: dict[str, list[RenderedMessage]] = {}
    for t in w.threads:
        msgs = render_thread(w, tl, t, seen, rng)
        rendered[t["thread_id"]] = msgs
        for m in msgs:
            write_eml(tl, m, inbox)
    bulk: dict[str, RenderedMessage] = {}
    for it in w.bulk:
        m = render_bulk_item(w, tl, it, seen, rng)
        bulk[it["id"]] = m
        write_eml(tl, m, inbox)
    cal_events = write_calendars(w, tl, out / "calendar", corrupt_work=corrupt_ics)
    notes = write_notes(w, tl, out)
    tasks = write_tasks(w, tl, out)
    return rendered, bulk, cal_events, notes, tasks


def category_counts(w: World) -> dict[str, int]:
    counts: dict[str, int] = {}
    for t in w.threads:
        counts[t.get("category") or "uncategorized"] = counts.get(t.get("category") or "uncategorized", 0) + len(t["messages"])
    for it in w.bulk:
        counts[it["category"]] = counts.get(it["category"], 0) + 1
    return counts


def generate(world: str = "dev", anchor: date | None = None, seed: int = 7, data_root: Path | None = None,
             manifest_root: Path | None = None, strict: bool = True) -> BuildResult:
    w = load_world(world)
    rep = Report()
    check_reviewed(w, rep)
    if rep.problems and strict:
        return BuildResult(data_dir=Path(), manifest_path=None, report=rep, emails=0, variants=[])
    anchor = anchor or w.anchor
    tl = Timeline(anchor)
    data_root = data_root or (REPO / "data")
    manifest_root = manifest_root or (REPO / "eval" / "manifests")
    out = data_root / world

    rendered, bulk, cal_events, notes, tasks = render_world(w, tl, out, seed)
    n_emails, _ids = check_inbox(out / "inbox", tl, rep)
    check_storyline_coverage(w, rendered, rep)
    check_must_include(w, rendered, bulk, notes, rep)
    check_prose_words(rendered, bulk, notes, rep)
    cats = category_counts(w)
    check_counts(w, cats, rep)
    counts = {"emails": n_emails, "notes": len(notes), "tasks": len(tasks["items"]),
              "events": sum(len(v) for v in cal_events.values()), **{f"cat:{k}": v for k, v in cats.items()}}
    manifest = build_manifest(w, tl, rendered, bulk, notes, tasks, cal_events, counts, datetime.now(TZ), seed, rep.problems)
    check_manifest_refs(manifest, rep)

    variant_dirs: list[Path] = []
    for s in w.storylines:
        for v in s.get("variants", []):
            w2 = _apply_variant(w, v["id"])
            vout = data_root / f"{world}__{v['id']}"
            render_world(w2, tl, vout, seed)
            check_inbox(vout / "inbox", tl, rep)
            variant_dirs.append(vout)

    manifest_path = manifest_root / f"{world}.yaml"
    if rep.ok() or not strict:
        manifest_root.mkdir(parents=True, exist_ok=True)
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(f"# GENERATED by `digest generate --world {world}` — the answer key. The digest never reads this file.\n")
            yaml.safe_dump(manifest.model_dump(mode="json", exclude_none=True), f, sort_keys=False, allow_unicode=True, width=120)
    else:
        manifest_path = None
    return BuildResult(data_dir=out, manifest_path=manifest_path, report=rep, emails=n_emails, variants=variant_dirs)
